### PR TITLE
updated test velocity templates for itemNode

### LINKED ISSUE #15: Refactor itemNode to consistently return objects to enable units

### PR DESCRIPTION
**Pull request by srlevoe**
Resolves #15

### CODE REVIEW

**Comment by jordanpadams** [comment]
@srlevoe can we make sure the docs are also valid with this change?

**Comment by jordanpadams** [comment]
@srlevoe also, can you provide some info on how this can be tested in the PR above? we need to make sure we can do proper I&T on this

**Comment by srlevoe** [comment]
https://github.com/jordanpadams I modified the test templates in src/test/resources/data so that all the tests in mvn test complete without errors. I don't know what ele to do for testing.

On the documentation question. I see the page: 
https://nasa-pds.github.io/mi-label/templates/index.html#PDS3_to_PDS4_Conversions
The template for this page is at https://github.com/NASA-PDS/mi-label/blob/master/src/site/xdoc/templates/index.xml.vm

The changes I think would be appropriate are:

Base Element
change from 

Velocity
<Subject_Area>
  <target_name>$label.TARGET_NAME</target_name>
</Subject_Area>

to

Velocity
<Subject_Area>
  <target_name>$label.TARGET_NAME.toString()</target_name>
</Subject_Area>

In the UNITS section

Velocity
<Geometry_Parameters>
  <azimuth units="$label.getUnits('INST_AZIMUTH')">$label.INST_AZIMUTH</azimuth>
</Geometry_Parameters>

to 

Velocity
<Geometry_Parameters>
  <azimuth units="$label.getUnits('INST_AZIMUTH')">$label.INST_AZIMUTH.toString()</azimuth>
</Geometry_Parameters>

Add an alternate method of getting units

Velocity
<Geometry_Parameters>
  <azimuth units=$label.INST_AZIMUTH.getUnits()>$label.INST_AZIMUTH.toString()</azimuth>
</Geometry_Parameters>

Is this what you arte looking for?

**Comment by srlevoe** [comment]
I have modified these files to work with the changes:   
Example templates
src/site/resources/examples/MPF_IMP_EDR7.vm
src/site/resources/examples/template_example.vm
documentation
src/site/xdoc/templates/index.xml.vm

**Comment by jordanpadams** [comment]
@srlevoe made a couple tweaks to your updates but looks good. can you add an explicit regression test for your the use case you are trying to accomplish here? want to make sure future updates don't break it.

**Pull request merged**
